# Setup
title:               Dissections
tagline:             'Picking thoughts apart'
description:         'My small home to make sense of the world. You can also find me on Twitter.'
url:                 http://bradartziniega.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Brad Artziniega
  url:               https://twitter.com/lightningboltz
  email:             bradley.artziniega@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
